from .chamfer_matching_function import ChamferMatching
from .diagonal_matching_function import DiagonalMatching
from .linear_matching_function import LinearMatching
from .max_matching_function import MaxMatching
from .mean_matching_function import MeanMatching
from .otam_matching_function import OTAMMatching